#!/bin/sh

CHEMIN="/srv/slam/scripts"
FILE="FeuxRouge"
FILE="$CHEMIN"/"$FILE"
if test -f "$FILE" ; then
        echo 'Une génération des fichiers de configuration par SLAM est en train de tourner, revenez plus tard.' 1>&2
        echo "Le fichier $FILE sur slam.lal.in2p3.fr existe." 1>&2
        exit 1
else
	REGEN_HOST="root@nis-server01"
	DNS_REGEN_CMD="cd /var/named/ && make"
	DHCP_REGEN_CMD="cd /mgt/dhcp/scripts/ && ./dhcp_rebuild_db"

	# launch SLAM
	cd /srv/slam
	export PATH="/root/slam/bin:$PATH"
	
	touch $FILE
	./src/slam_cli.py -a createconf
	if [ $? -ne 0  ]; then
		rm -f $FILE
		echo 'Problème lors de la génération des fichiers de configuration par SLAM.' 1>&2
		exit 1
	fi

	# asa or as3?
	# echo; ... | tail -1: avoid getting the ssh 'last login' message
	#named_asa=`ssh root@asa -t 'echo; ps x | grep named | grep -v grep | wc -l' | tail -1`
	#named_asa=`echo $named_asa | head -c 1`
	#named_as3=`ssh root@as3 -t 'echo; ps x | grep named | grep -v grep | wc -l' | tail -1`
	#named_as3=`echo $named_as3 | head -c 1`
	#if [ $named_asa -gt 0 ]; then
	#	REGEN_HOST="root@asa"
	#elif [ $named_as3 -gt 0 ]; then
	#	REGEN_HOST="root@as3"
	#else
	#	'Impossible de déterminer la machine sur laquelle est lancé le serveur DNS.' 1>&2
	#	exit 1
	#fi

	# DNS regeneration
	ssh "$REGEN_HOST" -t "$DNS_REGEN_CMD"
	if [ $? -ne 0 ]; then
		echo 'Erreur pendant la reconstruction de la base DNS.' 1>&2
		exit 1
	fi
	# DHCP regeneration
	ssh "$REGEN_HOST" -t "$DHCP_REGEN_CMD"
	if [ $? -ne 0 ]; then
		echo 'Erreur pendant la reconstruction de la base DHCP.' 1>&2
		exit 1
	fi
	rm -f $FILE
fi

